name: Sync Issue Labels

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

env:
  LABELS: |
    - name: <impl>
      color: 551199
      description: Track internal project development
    - name: bug
      color: 551111
      description: Unexpected and undesired behavior
    - name: chore
      color: 555533
      description: Refactoring and maintenance tasks
    - name: copy
      color: 555555
      description: Problem already noted in another item
    - name: doc
      color: 333399
      description: Enhance existing documentation
    - name: feat
      color: 447744
      description: New feature request or enhancement
    - name: help-wanted
      color: 335555
      description: Open to contribution from users
    - name: not-planned
      color: 000000
      description: Not planned and will not be worked on
    - name: stale
      color: 555555
      description: Closed due to insufficient activity
    - name: waiting
      color: 994422
      description: Waiting for feedback from author

jobs:
  sync-labels:
    name: Sync Labels with Specification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Analyze label sets
        run: |
          echo "$LABELS" | yq -r '.[].name' > /tmp/specification.txt
          gh label list --json name -q '.[].name' > /tmp/repository.txt
          # Set A: in spec, not in repo (create)
          comm -23 <(sort /tmp/specification.txt) <(sort /tmp/repository.txt) > /tmp/create.txt
          # Set B: in spec, in repo (update)
          comm -12 <(sort /tmp/specification.txt) <(sort /tmp/repository.txt) > /tmp/update.txt
          # Set C: not in spec, in repo (archive)
          comm -13 <(sort /tmp/specification.txt) <(sort /tmp/repository.txt) > /tmp/archive.txt

      - name: Create new labels
        run: |
          while read -r label; do
            echo "$LABELS" | \
            yq -r ".[] | select(.name == \"$label\") | [.name, .color, .description] | @tsv" | \
            while IFS=$'\t' read -r name color desc; do
              echo "Create new: $name"
              gh label create "$name" --color "$color" --description "$desc"
            done
          done < /tmp/create.txt

      - name: Update existing labels
        run: |
          while read -r label; do
            echo "$LABELS" | \
            yq -r ".[] | select(.name == \"$label\") | [.name, .color, .description] | @tsv" | \
            while IFS=$'\t' read -r name color desc; do
              echo "Update existing: $name"
              gh label edit "$name" --color "$color" --description "$desc"
            done
          done < /tmp/update.txt

      - name: Archive orphaned labels
        run: |
          archive_date=$(date +%Y%m%d)
          while read -r label; do
            if [[ "$label" =~ ^~~.+___[0-9]+$ ]]; then
              echo "Skip archived: $label"
              continue
            fi
            echo "Archive orphaned: $label -> ~~${label}___${archive_date}"
            gh label edit "$label" --name "~~${label}___${archive_date}"
          done < /tmp/archive.txt
